package com.adayo.app.setting.model.constant;

public class ParamConstant {
    public static final int CONFIGURATION_HM6C17A = 1;
    public static final int CONFIGURATION_HM6C18A = 2;
    public static final String FILE_CONFIG_HM6C17A = "HM6C17A/FactoryClass";
    public static final String FILE_CONFIG_HM6C18A = "HM6C18A/FactoryClass";
    public static final String HM6C17A = "HM6C17A";
    public static final String HM6C18A = "HM6C18A";
    public static final String COMMON = "Common";
    public static final String DEVNM = "Devnm";
    public static final String LOCAL = "Local";
    public static final String REPLY = "Reply";
    public static final String HOTSPOT = "Hotspot";
    public static final String UNIT = "Unit";
    public static final String WIFI = "Wifi";
    public static final String DIRECT_MEDIA = "DirectMedia";
    public static final String DRIVE = "Drive";
    public static final String LANGUAGE = "Language";
    public static final String BLUETOOTH = "Bluetooth";
    public static final String SYS_PROP_KEY_REBOOTED = "adayo.system.rebooted";
    public static final String SYS_PROP_VALUE_REBOOTED_F = "0";
    public static final String SYS_PROP_VALUE_REBOOTED_T = "1";
    public static final String MMKV_KEY_OL_UPGRADE_INFO = "ol_upgrade_info";
    public static final String SYS_PROP_KEY_SETTING_PAGE_SOFTWARE_VERSION = "adayo.settingPage.softwareVersion";
    public static final String SYS_PROP_VALUE_SETTING_PAGE_SOFTWARE_VERSION_F = "0";
    public static final String SYS_PROP_VALUE_SETTING_PAGE_SOFTWARE_VERSION_T = "1";
    public static final String SETTING_GLOBAL_KEY_PHONE_RING = "phone_ring";public static final int SETTING_GLOBAL_VALUE_PHONE_RING_RUNNING_WATER = 0;public static final int SETTING_GLOBAL_VALUE_PHONE_RING_MOUNTAIN_STREAM = 1;
    public static final int SETTING_GLOBAL_VALUE_PHONE_RING_STARRY_SKY = 2;
    public static final String SETTING_GLOBAL_KEY_KM_AND_OIL_WEAR_UNIT = "km_and_oil_wear_unit";public static final String STEERING_WHEEL_CUSTOM_MEDIA_BUTTONS = "steering_wheel_custom_media_buttons";
    public static final String MEDIA_SOURCE_SWITCHING = "media_source_switching";public static final String MEDIA_PLAY_PAUSE = "media_play_pause";public static final String OFF_ROAD_INFORMATION = "off_road_information";public static final String AI_QU_TING = "ai_qu_ting";public static final String NAVIGATION = "navigation";public static final String NAVIGATION_TONE = "navigation_tone";public static final String NAVIGATION_MUTE = "navigation_mute";public static final String GO_HOME = "go_home";public static final String GO_TO_COMPANY = "go_to_company";public static final String YUE_YE_CIRCLE = "yue_ye_circle";public static final String DRIVING_RECORDER = "driving_recorder";public static final String AIR_CONDITIONER = "air_conditioner";public static final String SCREEN_OFF = "screen_off";public static final String WIRELESS_CHARGING = "wireless_charging";public static final String SYSTEM_SETTINGS = "system_settings";public static final String YUE_YE_CIRCLE_INTERCOM = "yue_ye_circle_intercom";public static final int SETTING_GLOBAL_VALUE_KM_AND_OIL_WEAR_UNIT_METRIC = 0;public static final int SETTING_GLOBAL_VALUE_KM_AND_OIL_WEAR_UNIT_IMPERIAL = 1;
    public static final String SETTING_GLOBAL_KEY_TEMPERATURE_UNIT = "temperature_unit";public static final int SETTING_GLOBAL_VALUE_TEMPERATURE_UNIT_CELSIUS = 0;public static final int SETTING_GLOBAL_VALUE_TEMPERATURE_UNIT_FAHRENHEIT = 1;
    public static final String SYS_PROP_KEY_LOCATE_MODE = "persist.adayo.locate.mode";public static final int SYS_PROP_VALUE_LOCATE_MODE_DUAL = 0;public static final int SYS_PROP_VALUE_LOCATE_MODE_GPS = 1;
    public static final int SYS_PROP_VALUE_LOCATE_MODE_BEIDOU = 2;
    public static final int DLG_WINDOW_TYPE = 2080;
    public static final String TIME_FORMAT_12 = "yyyy/MM/dd hh:mma";
    public static final String TIME_FORMAT_24 = "yyyy/MM/dd HH:mm";
    public static final String INTENT_COMP_NAME_FTY_MODE = "com.adayo.app.factorymode";
    public static final String BDL_KEY_SOURCE_MNG = "map";
    public static final String BDL_KEY_SETTING_PAGE = "setting_page";public static final String BDL_VALUE_SETTING_PAGE_BT = "bt";public static final String BDL_VALUE_SETTING_PAGE_BT_MUSIC = "bt_music";public static final String BDL_VALUE_SETTING_PAGE_BT_PHONE = "bt_phone";public static final String BDL_VALUE_SETTING_PAGE_WIFI = "wifi";public static final String BDL_VALUE_SETTING_PAGE_HOTSPOT = "hotspot";public static final String BDL_VALUE_SETTING_PAGE_TIME = "time";public static final String BDL_VALUE_SETTING_PAGE_EQ = "eq";public static final String BDL_VALUE_SETTING_PAGE_UPG = "upgrade";public static final String BDL_KEY_TAB_ITEM = "tab_item";
    public static final String BDL_KEY_TAB_ITEM_SEL_POS = "tab_item_sel_pos";public static final String BDL_KEY_LIST_ITEM = "list_item";
    public static final String BDL_KEY_LIST_ITEM_SEL_POS = "list_item_sel_pos";
    public static final String BDL_KEY_DLG_TITLE = "dlg_title";
    public static final String BDL_KEY_DLG_ENABLELENGTH = "dlg_enable_length";
    public static final String BDL_KEY_DLG_MSG = "dlg_msg";
    public static final String BDL_KEY_DLG_POSITIVE = "dlg_positive";
    public static final String BDL_KEY_DLG_NEGATIVE = "dlg_negative";
    public static final String BDL_KEY_DLG_EDT_CONTENT = "dlg_edt_content";public static final String BDL_KEY_DLG_REPLY_CONTENT = "dlg_reply_content";public static final String BUS_TAG_LO_UPG_LATEST_VER = "lo_upg_latest_ver";
    public static final String BUS_TAG_OL_UPG_TSP_STATUS = "ol_upg_tsp_status";
    public static final String BUS_TAG_OL_UPG_LATEST_VER_BADGE = "ol_upg_latest_ver_badge";
    public static final String BUS_TAG_OL_UPG_LATEST_VER = "ol_upg_latest_ver";
    public static final String BUS_TAG_OL_UPG_LATEST_VER_PACKAGE_SIZE = "ol_upg_latest_ver_package_size";
    public static final String BUS_TAG_OL_UPG_LATEST_VER_DL_PROGRESS = "ol_upg_latest_ver_dl_progress";
    public static final String BUS_TAG_OL_UPG_LATEST_VER_DL_STATUS = "ol_upg_latest_ver_dl_status";
    public static final String ADAPTER_PAYLOAD_ITEM_VALUE = "item_value";
    public static final String ADAPTER_PAYLOAD_ITEM_ENABLE = "item_enable";
    public static final int SHARE_INFO_ID_EQ_AND_EFFECT = 2;public static final String SHARE_INFO_KEY_EQ_MODE = "sound_effect";public static final String SHARE_INFO_KEY_EQ_BAND = "freq_effect_arr";public static final String SHARE_INFO_KEY_SOUND_FIELD_X = "sound_filed_x";
    public static final String SHARE_INFO_KEY_SOUND_FIELD_Y = "sound_filed_y";
    public static final String SHARE_INFO_KEY_DTS_MODE = "best_audio_phoneme";
    public static final String SHARE_INFO_LOUDNESS_SWITCH = "loudness_switch";
    public static final String SHARE_INFO_KEY_DTS_MODE_LAST = "best_audio_phoneme_bass";
    public static final int SHARE_INFO_ID_LOUDNESS = 7;
    public static final int SHARE_INFO_ID_USB_UPGRADE = 2022;public static final String SHARE_INFO_KEY_BEEP = "sys_beep_switch";public static final String SHARE_INFO_KEY_HAS_UPGRADE_FILE = "hasUpgradeFile";public static final String SHARE_INFO_KEY_LOUDNESS_SPEED_COMPENSATE = "speed_compensate";public static final String SHARE_INFO_KEY_LOUDNESS = "audio_stream_arr";public static final int SHARE_INFO_ID_BT_CONN = 27;
    public static final String SHARE_INFO_KEY_BT_ENABLE = "is_bt_enabled";
    public static final String SHARE_INFO_KEY_BT_PHONE_NAME = "phoneName";
    public static final int SHARE_INFO_ID_TIME = 8;public static final String SHARE_INFO_KEY_TIME_NET_SYNC = "network_sync";public static final String SHARE_INFO_KEY_TIME_GPS_SYNC = "gps_sync";public static final String SHARE_INFO_KEY_TIME_24_CLOCK_MODE = "is24Hour";public static final int SHARE_INFO_ID_DISPLAY = 10;public static final String SHARE_INFO_KEY_LIGHTNESS = "brightness";public static final String SHARE_INFO_KEY_LIGHTNESS_MODE = "day_night_mode";public static final int SHARE_INFO_ID_GENERAL = 11;public static final String SHARE_INFO_KEY_DRIVING_VIDEO = "driving_watch_video_switch";public static final String SHARE_INFO_KEY_LANGUAGE = "sys_lang";public static final String SHARE_INFO_KEY_THEME_MODE = "system_theme_mode";public static final int SHARE_INFO_ID_WAKE = 435;public static final String SHARE_INFO_KEY_WAKE_SWITCH = "mainWakeUp";public static final String SHARE_INFO_KEY_WAKE_WORD = "customWord";public static final String SHARE_INFO_KEY_WAKE_ROLE = "roleId";public static final String SHARE_INFO_KEY_PARTIALLY_WAKEUP = "partiallyWakeUp";public static final String REPLY_SWITCH = "reply_switch";public static final String REPLY_SWITCH_OWE = "reply_switch_owe";public static final String REPLY_BUTTON = "reply_button";public static final String REPLY_EDIT = "reply_edit";public static final String REPLY_EDIT_OWE = "reply_edit_OWE";public static final String REPLY_AUTOMATIC = "我正在开车，稍后给你回复";public static final String REPLY_EDIT_MOREN = "我马上会打给你";public static final String SKIN = "persist.adayo.sys.skin";public static final String FACTORY_MODE = "ro.adayo.factory.password";public static final Integer HIGHLIGHT_NO = 0;public static final Integer HIGHLIGHT_DEVNM = 1;public static final Integer HIGHLIGHT_HOTSPOT = 2;public static final Integer HIGHLIGHT_WIFI = 3;public static final Integer HIGHLIGHT_BT = 4;public static final Integer HIGHLIGHT_REPLY = 5;public static final Integer HIGHLIGHT_UNIT = 6;public static final Integer HIGHLIGHT_BGLOCAL = 7;public static final Integer HIGHLIGHT_BGLANGUAGE = 8;public static final Integer HIGHLIGHT_BGDRIVE = 9;public static final Integer HIGHLIGHT_DIECT_MEDIA = 10;public static final Integer HIGHLIGHT_SOUND_LOUDNESS = 11;public static final Integer HIGHLIGHT_SOUND_SWITCH = 12;public static final Integer HIGHLIGHT_SOUND_EQ = 13;public static final Integer HIGHLIGHT_HARMAN = 14;public static final Integer HIGHLIGHT_DISPLAY_SET_LIGHTNESS = 15;public static final Integer HIGHLIGHT_DISPLAY_SET_TIME = 16;public static final Integer HIGHLIGHT_DISPLAY_SET_THEME = 17;public static final Integer HIGHLIGHT_DISPLAY_SET_STANDBY = 18;public static final Integer HIGHLIGHT_VOICE = 19;public static final Integer HIGHLIGHT_SYSTEM_MESSAGE = 20;public static final Integer HIGHLIGHT_UPGRADE = 21;public static final Integer HIGHLIGHT_BGLANGUAGE_DESTROY = 22;public static final Integer WIFI_UI_STATE_NO_SAVE_ITEM = 1;public static final Integer WIFI_UI_STATE_NO_WLAN_ITEM = 2;public static final Integer WIFI_UI_STATE_SAVE_ITEM = 3;public static final Integer WIFI_UI_STATE_WLAN_ITEM = 4;public static final String BT_NAME = "bt_name";
    public static final String Wireless_Charging = "WirelessCharging";public static final String Vehicle_UI = "VehicleUI";
    public static final String HOTSPOT_SWITCH = "app_setting_hotspot_switch";
    public static final String HamanPowerIcon = "HamanPowerIcon";

    public static final String VR_ACTION_IS_DUPLEX_ENABLE = "isDuplexEnable";
    public static final String VR_ACTION_SET_DUPLEX_ENABLED = "setDuplexEnabled";
    public static final String VR_ACTION_GET_DUPLEX_ACTIVE_TIME = "getDuplexActiveTime";
    public static final String VR_ACTION_SET_DUPLEX_ACTIVE_TIME = "setDuplexActiveTime";
    public static final String VR_ACTION_IS_SHOW_VALID_RESULT = "isShowValidResult";
    public static final String VR_ACTION_SET_DUPLEX_VALID_RESULT = "setDuplexValidResult";

}